services:

  server:
    container_name: fastapi_app
    build: .
    ports:
      - "8000:8000"
#    volumes:
#      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

    command: poetry run uvicorn main:main_app --host 0.0.0.0 --port 8000
#    depends_on:
#      - pg


  pg:
    container_name: pg_fastapi
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: gas
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: car_service
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"


  adminer:
    image: adminer
    ports:
      - "8080:8080"

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5054:80"