"""add tools

Revision ID: 824970e6c6e4
Revises: be717fe3fd15
Create Date: 2024-09-18 15:33:03.674923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "824970e6c6e4"
down_revision: Union[str, None] = "be717fe3fd15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tool",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("diameter", sa.Float(), nullable=False),
        sa.Column("lenght", sa.Float(), nullable=False),
        sa.Column("deep_of_drill", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tool")
    # ### end Alembic commands ###
