"""delete plate and screw

Revision ID: 36bfa6181e81
Revises: 27109e434de4
Create Date: 2024-10-28 12:46:58.650759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "36bfa6181e81"
down_revision: Union[str, None] = "27109e434de4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("drill_archive", "plate")
    op.drop_column("drill_archive", "screw")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drill_archive",
        sa.Column("screw", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "drill_archive",
        sa.Column("plate", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
