"""add desc

Revision ID: 7106b74dc00a
Revises: 0d5b862f1cf2
Create Date: 2024-09-30 13:02:07.158593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7106b74dc00a"
down_revision: Union[str, None] = "0d5b862f1cf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drill", sa.Column("length_xD", sa.Float(), nullable=True))
    op.add_column("drill", sa.Column("screw", sa.String(), nullable=True))
    op.add_column(
        "drill", sa.Column("description", sa.String(), nullable=True)
    )
    op.drop_column("drill", "screws")
    op.drop_column("drill", "length")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drill",
        sa.Column(
            "length",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "drill",
        sa.Column("screws", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("drill", "description")
    op.drop_column("drill", "screw")
    op.drop_column("drill", "length_xD")
    # ### end Alembic commands ###
