"""del foo\bar

Revision ID: fe6cc83cd5f3
Revises: cc81552ebf20
Create Date: 2024-08-08 22:11:58.014525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fe6cc83cd5f3"
down_revision: Union[str, None] = "cc81552ebf20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_foo", "users", type_="unique")
    op.drop_column("users", "bar")
    op.drop_column("users", "foo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("foo", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "users",
        sa.Column("bar", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_unique_constraint("uq_users_foo", "users", ["foo", "bar"])
    # ### end Alembic commands ###
