"""add many-to-many to screws and drills

Revision ID: dd813d1da584
Revises: bc479c7831c8
Create Date: 2024-10-01 15:56:28.823970

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd813d1da584"
down_revision: Union[str, None] = "bc479c7831c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drill_screw_association",
        sa.Column("drill_id", sa.Integer(), nullable=False),
        sa.Column("screw_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drill_id"],
            ["drill.id"],
            name=op.f("fk_drill_screw_association_drill_id_drill"),
        ),
        sa.ForeignKeyConstraint(
            ["screw_id"],
            ["screw.id"],
            name=op.f("fk_drill_screw_association_screw_id_screw"),
        ),
        sa.PrimaryKeyConstraint(
            "drill_id", "screw_id", name=op.f("pk_drill_screw_association")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drill_screw_association")
    # ### end Alembic commands ###
