"""add c.role to table.users and auth

Revision ID: 5c7b8e27d0b4
Revises: 016553ef8e1c
Create Date: 2024-10-04 02:58:45.000099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c7b8e27d0b4"
down_revision: Union[str, None] = "016553ef8e1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from sqlalchemy.dialects import postgresql

# Определяем ENUM тип
role_enum = postgresql.ENUM("NOOB", "MASTER", "BOSS", name="roleenum")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем тип ENUM
    role_enum.create(op.get_bind())
    # Добавляем столбец с новым типом
    op.add_column("user", sa.Column("role", role_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Удаляем столбец
    op.drop_column("user", "role")
    # Удаляем ENUM тип
    role_enum.drop(op.get_bind())
