"""del unique for User.name

Revision ID: 6a5b30fb9615
Revises: 0deca3f087e4
Create Date: 2024-08-14 13:50:45.623867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6a5b30fb9615"
down_revision: Union[str, None] = "0deca3f087e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_username", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_username", "user", ["username"])
    # ### end Alembic commands ###
