"""add table drill archive

Revision ID: 5335820e2415
Revises: 421617e53a21
Create Date: 2024-10-01 14:29:57.565659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5335820e2415"
down_revision: Union[str, None] = "421617e53a21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drill_archive",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("diameter", sa.Float(), nullable=True),
        sa.Column("length_xD", sa.Float(), nullable=True),
        sa.Column("deep_of_drill", sa.Float(), nullable=True),
        sa.Column("plate", sa.String(), nullable=True),
        sa.Column("screw", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("is_broken", sa.Boolean(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("storage", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drill_archive")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drill_archive")
    # ### end Alembic commands ###
