"""fix key_ to key

Revision ID: 5408eebb226e
Revises: 5c7b8e27d0b4
Create Date: 2024-10-05 21:50:38.333211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5408eebb226e"
down_revision: Union[str, None] = "5c7b8e27d0b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drill", sa.Column("key", sa.String(), nullable=True))
    op.drop_column("drill", "key_")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drill",
        sa.Column("key_", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("drill", "key")
    # ### end Alembic commands ###
