"""add foo and bar column

Revision ID: e5f4feb9e397
Revises: 6a41cc324d88
Create Date: 2024-08-06 19:36:20.892003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5f4feb9e397"
down_revision: Union[str, None] = "6a41cc324d88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("foo", sa.String(), nullable=False))
    op.add_column("users", sa.Column("bar", sa.String(), nullable=False))
    op.create_unique_constraint(op.f("uq_users_foo"), "users", ["foo", "bar"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_foo"), "users", type_="unique")
    op.drop_column("users", "bar")
    op.drop_column("users", "foo")
    # ### end Alembic commands ###
