"""refact role=unique

Revision ID: 27109e434de4
Revises: 2f7bb5ce7431
Create Date: 2024-10-16 15:52:53.461150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "27109e434de4"
down_revision: Union[str, None] = "2f7bb5ce7431"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_role_role"), "role", ["role"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_role_role"), "role", type_="unique")
    # ### end Alembic commands ###
