"""add rate and coordinates

Revision ID: b7fb934b5581
Revises: 5f865dbab722
Create Date: 2024-08-11 20:32:30.662745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7fb934b5581"
down_revision: Union[str, None] = "5f865dbab722"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies", sa.Column("coordinates", sa.JSON(), nullable=True)
    )
    op.add_column("services", sa.Column("comment", sa.String(), nullable=True))
    op.add_column("services", sa.Column("rate", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services", "rate")
    op.drop_column("services", "comment")
    op.drop_column("companies", "coordinates")
    # ### end Alembic commands ###
