"""added image, create_at and other

Revision ID: bdb38a59c5b5
Revises: b273dd9442ee
Create Date: 2024-09-26 07:16:55.009582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bdb38a59c5b5"
down_revision: Union[str, None] = "b273dd9442ee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tool", sa.Column("image_path", sa.String(), nullable=True))
    op.add_column("tool", sa.Column("storage", sa.String(), nullable=True))
    op.add_column(
        "tool",
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "tool",
        sa.Column(
            "update_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool", "update_at")
    op.drop_column("tool", "create_at")
    op.drop_column("tool", "storage")
    op.drop_column("tool", "image_path")
    # ### end Alembic commands ###
