"""fix length

Revision ID: 46a18160df62
Revises: 13e436e2f72d
Create Date: 2024-09-25 02:35:35.956689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "46a18160df62"
down_revision: Union[str, None] = "13e436e2f72d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tool", sa.Column("length", sa.Float(), nullable=True))
    op.drop_column("tool", "lenght")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tool",
        sa.Column(
            "lenght",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("tool", "length")
    # ### end Alembic commands ###
