"""fix drills

Revision ID: e08de0a44726
Revises: dd813d1da584
Create Date: 2024-10-01 16:20:57.580085

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e08de0a44726"
down_revision: Union[str, None] = "dd813d1da584"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("drill", "screw")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drill",
        sa.Column("screw", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
