"""del rate comment

Revision ID: 0deca3f087e4
Revises: 04d21077f456
Create Date: 2024-08-13 14:54:45.409799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0deca3f087e4"
down_revision: Union[str, None] = "04d21077f456"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("service", "rate")
    op.drop_column("service", "comment")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service",
        sa.Column("comment", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "service",
        sa.Column("rate", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
