"""Initial

Revision ID: d9c13cd53070
Revises: 
Create Date: 2024-10-03 13:39:29.573192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9c13cd53070"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("coordinates", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company")),
    )
    op.create_table(
        "drill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("diameter", sa.Float(), nullable=True),
        sa.Column("length_xD", sa.Float(), nullable=True),
        sa.Column("deep_of_drill", sa.Float(), nullable=True),
        sa.Column("plate", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("is_broken", sa.Boolean(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("storage", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drill")),
    )
    op.create_table(
        "drill_archive",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("diameter", sa.Float(), nullable=True),
        sa.Column("length_xD", sa.Float(), nullable=True),
        sa.Column("deep_of_drill", sa.Float(), nullable=True),
        sa.Column("plate", sa.String(), nullable=True),
        sa.Column("screw", sa.String(), nullable=True),
        sa.Column("key", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("is_broken", sa.Boolean(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("storage", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drill_archive")),
    )
    op.create_table(
        "screw",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("length", sa.Float(), nullable=True),
        sa.Column("thread", sa.String(), nullable=True),
        sa.Column("step_of_thread", sa.Float(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screw")),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "registration_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "drill_screw_association",
        sa.Column("drill_id", sa.Integer(), nullable=False),
        sa.Column("screw_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drill_id"],
            ["drill.id"],
            name=op.f("fk_drill_screw_association_drill_id_drill"),
        ),
        sa.ForeignKeyConstraint(
            ["screw_id"],
            ["screw.id"],
            name=op.f("fk_drill_screw_association_screw_id_screw"),
        ),
        sa.PrimaryKeyConstraint(
            "drill_id", "screw_id", name=op.f("pk_drill_screw_association")
        ),
    )
    op.create_table(
        "service",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
            name=op.f("fk_service_company_id_company"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_service")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service")
    op.drop_table("drill_screw_association")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_table("screw")
    op.drop_table("drill_archive")
    op.drop_table("drill")
    op.drop_table("company")
    # ### end Alembic commands ###
