"""create tables

Revision ID: 4fc1d607508c
Revises: 
Create Date: 2024-08-11 18:26:39.023678

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4fc1d607508c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),

        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),

        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
    )

    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),

        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),

        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),

        sa.Column("username", sa.String(), nullable=False),
        sa.Column("second_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),

        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("services")
    op.drop_table("companies")
    # ### end Alembic commands ###
