"""add table screws

Revision ID: bc479c7831c8
Revises: 5335820e2415
Create Date: 2024-10-01 15:53:35.652167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc479c7831c8"
down_revision: Union[str, None] = "5335820e2415"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screw",
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("length", sa.Float(), nullable=True),
        sa.Column("thread", sa.String(), nullable=True),
        sa.Column("step_of_thread", sa.Float(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "create_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screw")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("screw")
    # ### end Alembic commands ###
