"""del role

Revision ID: d76aee862e8c
Revises: 5408eebb226e
Create Date: 2024-10-16 14:23:43.211378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d76aee862e8c"
down_revision: Union[str, None] = "5408eebb226e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("drill", "plate")
    op.add_column("user", sa.Column("second_name", sa.String(), nullable=True))
    op.drop_column("user", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "role",
            postgresql.ENUM("NOOB", "MASTER", "BOSS", name="roleenum"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("user", "second_name")
    op.add_column(
        "drill",
        sa.Column("plate", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
