"""add is_broken

Revision ID: 13e436e2f72d
Revises: 234a58cd44e8
Create Date: 2024-09-24 21:35:57.527683

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13e436e2f72d"
down_revision: Union[str, None] = "234a58cd44e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tool", sa.Column("is_broken", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool", "is_broken")
    # ### end Alembic commands ###
