name: Example workflow file

on:
  push:
    branches:
      - main

jobs:
  remote-command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run remote command via SSH
      uses: D3rHase/ssh-command-action@latest
      with:
        host: ${{ secrets.SSH_HOST}}
        user: ${{ secrets.SSH_USER }}
        private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        host_fingerprint: ${{ secrets.INPUT_HOST_FINGERPRINT }}
        command: echo 'Hello, World!'

    - name: Notify Command Success
      run: echo "Command executed on ${{ secrets.HOST }} successfully!"
